(()=>{
'use strict';
let enabled=true,ctx,master,echo,timer,next=0,beat=0,noise;
try{enabled=localStorage.getItem('hyugajung-music')!=='off';beat=Number(sessionStorage.getItem('hyugajung-beat')||0)%128}catch{}
const button=document.createElement('button');button.type='button';button.className='sound-toggle';document.body.append(button);
const step=60/118/2;
// Original 16-bar composition, with plucked chords, mallets, bass and light drums.
const chords=[[60,64,67],[57,60,64],[53,57,60],[55,59,62],[60,64,67],[57,60,64],[53,57,60],[55,59,62],[65,69,72],[60,64,67],[57,60,64],[55,59,62],[65,69,72],[60,64,67],[55,59,62],[60,64,67]];
const melody=[[76,0,79,76,74,72,0,74],[76,0,72,69,72,0,76,0],[77,0,76,74,72,0,69,72],[74,0,71,67,71,74,0,0],[76,79,0,81,79,76,74,72],[76,0,72,0,69,72,76,0],[77,76,74,0,72,69,72,74],[71,0,74,0,79,0,0,0],[81,0,79,77,76,77,0,79],[79,0,76,72,76,0,79,0],[81,79,76,0,72,0,76,0],[74,0,71,74,79,0,77,76],[77,0,81,79,77,76,74,72],[76,0,79,76,72,0,74,76],[74,71,67,71,74,77,76,74],[72,0,76,0,79,0,72,0]];
function label(){const running=enabled&&ctx?.state==='running';button.textContent=!enabled?'♪ 음악 꺼짐':running?'♫ 음악 켜짐':'♫ 음악 시작';button.setAttribute('aria-pressed',String(enabled));button.setAttribute('aria-label',!enabled?'배경음악 켜기':running?'배경음악 끄기':'배경음악 시작하기');button.title='휴가중 오리지널 여행 테마 · 배경음악과 효과음';}
function setup(){if(ctx)return;const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;ctx=new Audio();const compressor=ctx.createDynamicsCompressor();compressor.threshold.value=-18;compressor.ratio.value=3;master=ctx.createGain();master.gain.value=.32;master.connect(compressor);compressor.connect(ctx.destination);const delay=ctx.createDelay(.5);delay.delayTime.value=step*.75;echo=ctx.createGain();echo.gain.value=.12;echo.connect(delay);delay.connect(master);noise=ctx.createBuffer(1,ctx.sampleRate*.3,ctx.sampleRate);const a=noise.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=Math.random()*2-1;ctx.onstatechange=()=>{if(ctx.state==='running'&&enabled&&!document.hidden){if(!timer){next=ctx.currentTime+.04;timer=setInterval(schedule,60);schedule()}}else{clearInterval(timer);timer=undefined}label()};}
function note(midi,time,duration,volume,kind='pluck'){const frequency=440*2**((midi-69)/12),gain=ctx.createGain(),filter=ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.setValueAtTime(kind==='bass'?650:4200,time);filter.frequency.exponentialRampToValueAtTime(kind==='bass'?220:850,time+duration);gain.gain.setValueAtTime(.0001,time);gain.gain.exponentialRampToValueAtTime(volume,time+.007);gain.gain.exponentialRampToValueAtTime(.0001,time+duration);filter.connect(gain);gain.connect(master);if(kind==='mallet')gain.connect(echo);const o=ctx.createOscillator();o.type=kind==='bass'?'sine':'triangle';o.frequency.value=frequency;o.connect(filter);o.start(time);o.stop(time+duration+.02);if(kind==='mallet'){const v=ctx.createOscillator(),g=ctx.createGain();v.frequency.value=frequency*2;g.gain.setValueAtTime(volume*.22,time);g.gain.exponentialRampToValueAtTime(.0001,time+.12);v.connect(g);g.connect(master);v.start(time);v.stop(time+.14)}}
function drum(time,snare){if(!snare){const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.setValueAtTime(135,time);o.frequency.exponentialRampToValueAtTime(48,time+.13);g.gain.setValueAtTime(.2,time);g.gain.exponentialRampToValueAtTime(.0001,time+.16);o.connect(g);g.connect(master);o.start(time);o.stop(time+.17)}else{const s=ctx.createBufferSource(),f=ctx.createBiquadFilter(),g=ctx.createGain();s.buffer=noise;f.type='highpass';f.frequency.value=1500;g.gain.setValueAtTime(.075,time);g.gain.exponentialRampToValueAtTime(.0001,time+.085);s.connect(f);f.connect(g);g.connect(master);s.start(time);s.stop(time+.09)}}
function schedule(){if(!enabled||ctx.state!=='running'||document.hidden)return;while(next<ctx.currentTime+.18){const bar=Math.floor(beat/8)%16,eighth=beat%8,chord=chords[bar],t=next+(eighth%2?.015:0);if(eighth%2===0){chord.forEach((n,i)=>note(n,t+i*.013,.28,.048));note(chord[0]-24+(eighth===4?7:0),t,.3,.16,'bass');drum(t,eighth===2||eighth===6)}if(melody[bar][eighth])note(melody[bar][eighth],t,.28,.11,'mallet');beat=(beat+1)%128;next+=step;}}
function start(){if(!enabled||document.hidden)return;setup();if(ctx){master.gain.value=.32;ctx.resume().then(()=>{if(enabled&&ctx.state==='running'&&!timer){next=ctx.currentTime+.04;timer=setInterval(schedule,60);schedule()}label()}).catch(()=>label())}}
function stop(){clearInterval(timer);timer=undefined;if(ctx){master.gain.setTargetAtTime(.0001,ctx.currentTime,.015);ctx.suspend()}label()}
button.addEventListener('click',()=>{if(enabled&&ctx?.state!=='running'){start();return;}enabled=!enabled;try{localStorage.setItem('hyugajung-music',enabled?'on':'off')}catch{}if(enabled)start();else stop();label()});
function unlock(event){if(event.target.closest?.('.sound-toggle'))return;if(enabled&&ctx?.state!=='running')start()}
document.addEventListener('pointerdown',unlock);document.addEventListener('keydown',event=>{if(['Enter',' '].includes(event.key))unlock(event)});document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();else if(enabled)start()});window.addEventListener('pagehide',()=>{try{sessionStorage.setItem('hyugajung-beat',String(beat))}catch{}stop()});window.tripSound=(kind,index=0)=>{if(!enabled||ctx?.state!=='running'||document.hidden)return;if(kind==='win')[72,76,79,84].forEach((n,i)=>note(n,ctx.currentTime+i*.12,.32,.16,'mallet'));else if(kind==='draw'){const t=ctx.currentTime,pitch=[79,81,79,84,81,84,86,84,81,84,86,84,88][index%13];note(pitch,t,.085,.25,'pluck');note(pitch-12,t,.055,.08,'bass')}};label();start();
})();
